import { createContext, useContext, useState, useEffect, ReactNode } from 'react'
import { docTranslations } from '../constants/docTranslations'

export type Language = 'en' | 'zh'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const STORAGE_KEY = 'dockpull-language'

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.overview': 'Overview',
    'nav.images': 'Images',
    'nav.logs': 'Logs',
    'nav.settings': 'Settings',
    'nav.docs': 'Docs',
    'search.placeholder': 'Search...',
    'search.noResults': 'No results found for',
    'search.hint': 'Type to start searching',
    'theme.light': 'Switch to light mode',
    'theme.dark': 'Switch to dark mode',
    'lang.switch': 'Switch language',
    'lang.en': 'English',
    'lang.zh': '中文',

    'settings.title': 'Settings',
    'settings.tab.account': 'Account',
    'settings.tab.export': 'Export',
    'settings.tab.tokens': 'Tokens',
    'settings.tab.webhook': 'Webhook',
    'settings.account.title': 'Account Settings',
    'settings.account.subtitle': 'Manage your account credentials and password.',
    'settings.export.title': 'Export Settings',
    'settings.export.subtitle': 'Configure export path, platform, and pull behavior.',
    'settings.tokens.title': 'Access Tokens',
    'settings.tokens.subtitle': 'Configure authentication tokens for container registries.',
    'settings.webhook.title': 'Webhook Notifications',
    'settings.webhook.subtitle': 'Configure notifications for pull completion and failures.',
    'settings.loading': 'Loading configuration...',
    'settings.save': 'Save',
    'settings.saving': 'Saving...',
    'settings.saved': 'Saved',
    'settings.failed': 'Failed',
    'settings.test': 'Test',
    'settings.testing': 'Testing...',
    'settings.sent': 'Sent',
    'settings.password.success': 'Password changed successfully',
    'settings.password.minLength': 'New password must be at least 6 characters',
    'settings.password.mismatch': 'New passwords do not match',
    'settings.password.old': 'Old Password',
    'settings.password.oldHint': 'Enter your current password.',
    'settings.password.oldPlaceholder': 'Enter old password',
    'settings.password.new': 'New Password',
    'settings.password.newHint': 'New password must be at least 6 characters.',
    'settings.password.newPlaceholder': 'Enter new password',
    'settings.password.confirm': 'Confirm New Password',
    'settings.password.confirmHint': 'Re-enter your new password to confirm.',
    'settings.password.confirmPlaceholder': 'Confirm new password',
    'settings.export.directory': 'Export Directory',
    'settings.export.directoryHint': 'Directory where pulled images are saved.',
    'settings.export.browse': 'Browse',
    'settings.export.platform': 'Default Platform',
    'settings.export.platformHint': 'Target architectures for image pulls.',
    'settings.export.concurrent': 'Concurrent Pulls',
    'settings.export.concurrentHint': 'Max simultaneous pulls (1-10).',
    'settings.export.gzip': 'Gzip Compression',
    'settings.export.gzipHint': 'Compression level (1-9).',
    'settings.export.retries': 'Max Retries',
    'settings.export.retriesHint': 'Set 0 for unlimited retries.',
    'settings.export.retryInterval': 'Retry Interval (s)',
    'settings.export.retryIntervalHint': 'Seconds between each attempt.',
    'settings.webhook.enable': 'Enable Webhooks',
    'settings.webhook.enableHint': 'Send a POST request when pulls finish.',
    'settings.webhook.enabled': 'Enabled',
    'settings.webhook.disabled': 'Disabled',
    'settings.webhook.type': 'Webhook Type',
    'settings.webhook.typeHint': 'Platform to deliver notifications to.',
    'settings.webhook.url': 'Webhook URL',
    'settings.webhook.urlHint': 'Endpoint to POST notification payloads.',
    'settings.tokens.none': 'No registry tokens configured',
    'settings.tokens.add': 'Add Registry Token',
    'settings.tokens.addAnother': 'Add Another Registry',
    'settings.tokens.select': 'Select a registry to add:',
    'settings.tokens.allConfigured': 'All registries are already configured',
    'settings.tokens.remove': 'Remove',
    'settings.tokens.close': 'Close',

    'token.dockerhub.name': 'Docker Hub',
    'token.dockerhub.hint': 'Username and access token for Docker Hub (hub.docker.com). Create token at Account Settings > Security.',
    'token.dockerhub.username': 'Username',
    'token.dockerhub.token': 'Access token',
    'token.ghcr.name': 'GitHub Container Registry (ghcr.io)',
    'token.ghcr.hint': 'Personal access token with read:packages scope. Required even for public images.',
    'token.ghcr.token': 'ghp_xxxxxxxxxxxx',
    'token.quay.name': 'Quay.io',
    'token.quay.hint': 'Access token for Quay.io registry. Create robot account or use OAuth token.',
    'token.quay.token': 'Quay access token',
    'token.acr.name': 'Alibaba Container Registry (acr)',
    'token.acr.hint': 'Username and password for Alibaba Cloud Container Registry (cr.aliyun.com).',
    'token.acr.username': 'Username',
    'token.acr.password': 'Password',
    'token.ecr.name': 'AWS ECR',
    'token.ecr.hint': 'AWS credentials for Elastic Container Registry. Region defaults to us-east-1.',
    'token.ecr.accessKey': 'Access Key ID',
    'token.ecr.secretKey': 'Secret Access Key',
    'token.ecr.region': 'Region (e.g., us-east-1)',
    'token.gar.name': 'Google Artifact Registry (gar)',
    'token.gar.hint': 'Service account JSON key or OAuth token for Google Artifact Registry.',
    'token.gar.token': 'Google Cloud token or JSON key',

    'images.title': 'Images',
    'images.add': 'Add',
    'images.table.image': 'Image',
    'images.table.platform': 'Platform',
    'images.table.status': 'Status',
    'images.table.retries': 'Retries',
    'images.table.exportStatus': 'Export Status',
    'images.table.created': 'Created',
    'images.table.actions': 'Actions',
    'images.exported': 'Exported',
    'images.retry': 'Retry',
    'images.download': 'Download',
    'images.delete': 'Delete',
    'images.empty.title': 'Pull from any container registry',
    'images.empty.desc': 'Add images from Docker Hub, GitHub, Quay, or GCR to manage and distribute centrally.',
    
    'modal.addImage': 'Add Image',
    'modal.batchMode': 'Batch mode — one image per line',
    'modal.images': 'Images',
    'modal.image': 'Image',
    'modal.platforms': 'Platforms',
    'modal.autoExport': 'Auto-export after pull completes',
    'modal.cancel': 'Cancel',
    'modal.save': 'Save',
    'modal.saving': 'Saving...',
    
    'logs.title': 'Logs',
    'logs.refresh': 'Refresh',
    'logs.searchPlaceholder': 'Search logs...',
    'logs.allPlatforms': 'All Platforms',
    'logs.allImages': 'All Images',
    'logs.allActions': 'All Actions',
    'logs.clearFilters': 'Clear filters',
    'logs.table.time': 'Time',
    'logs.table.image': 'Image',
    'logs.table.action': 'Action',
    'logs.table.message': 'Message',
    'logs.loading': 'Loading logs...',
    'logs.empty.title': 'No logs found',
    'logs.empty.desc': 'Try adjusting your filters',
    'logs.empty.noLogs': 'Logs will appear here as images are processed',
    
    'stats.title': 'Overview',
    'stats.total': 'Total Images',
    'stats.totalDesc': 'All time image tasks',
    'stats.success': 'Successful',
    'stats.successDesc': 'Pulled successfully',
    'stats.failed': 'Failed',
    'stats.failedDesc': 'Pull failed',
    'stats.pending': 'Pending',
    'stats.pendingDesc': 'Queued or in progress',
    'stats.successRate': 'Success Rate',
    'stats.successRateDesc': 'Based on {count} total task(s)',
    'stats.legend.success': 'Success',
    'stats.legend.failed': 'Failed',
    'stats.legend.pending': 'Pending',
    
    'login.title': 'Sign In',
    'login.subtitle': 'Enter your credentials to access the system',
    'login.username': 'Username',
    'login.usernamePlaceholder': 'Enter your username',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.submit': 'Sign In',
    'login.submitting': 'Signing in...',
    'login.or': 'or',
    'login.sso': 'Continue with SSO',
    'login.newUser': 'New to DockerPull?',
    'login.requestAccess': 'Request access',
    'login.invalidCredentials': 'Invalid username or password',
    'login.error': 'An error occurred. Please try again.',
    'login.brandTitle': 'DockerPull',
    'login.brandDesc': 'A lightweight Docker image management system for pulling and organizing container images with ease',
    
    'status.pending': 'Pending',
    'status.pulling': 'Pulling',
    'status.success': 'Success',
    'status.failed': 'Failed',
    
    'platform.amd64': 'AMD64',
    'platform.arm64': 'ARM64',
    
    'action.created': 'Created',
    'action.updated': 'Updated',
    'action.pulling': 'Pulling',
    'action.success': 'Success',
    'action.failed': 'Failed',
    'action.exporting': 'Exporting',
    'action.exported': 'Exported',
    'action.changed': 'Changed',
    
    'toast.imageNoArm64': 'Image does not support linux/arm64, pulling linux/amd64 only',
    'toast.unableVerify': 'Unable to verify image architecture, continuing with selected platforms',
    'toast.tasksSkipped': '{count} task(s) skipped (already exists), {added} task(s) added',
    'toast.tasksAdded': 'Added {count} image task(s)',
    
    'copy.copied': 'Copied!',
    'copy.copyName': 'Copy image name',

    'user.admin': 'Administrator',
    'user.clickChange': 'Click avatar to change',
    'user.logout': 'Log out',
    'user.uploadValid': 'Please upload a valid image file (JPEG, PNG, GIF, WebP, BMP)',
    'user.fileSize': 'File size must be less than 10MB',

    'dirPicker.title': 'Select Directory',
    'dirPicker.subtitle': 'Choose where to save exported images',
    'dirPicker.quickAccess': 'Quick Access',
    'dirPicker.name': 'Name',
    'dirPicker.dateModified': 'Date modified',
    'dirPicker.type': 'Type',
    'dirPicker.cancel': 'Cancel',
    'dirPicker.select': 'Select',
    'dirPicker.loadFailed': 'Failed to load directory',

    ...docTranslations.en,
  },
  zh: {
    'nav.overview': '概览',
    'nav.images': '镜像',
    'nav.logs': '日志',
    'nav.settings': '设置',
    'nav.docs': '文档',
    'search.placeholder': '搜索...',
    'search.noResults': '未找到相关结果',
    'search.hint': '输入开始搜索',
    'theme.light': '切换到浅色模式',
    'theme.dark': '切换到深色模式',
    'lang.switch': '切换语言',
    'lang.en': 'English',
    'lang.zh': '中文',

    'settings.title': '设置',
    'settings.tab.account': '账户',
    'settings.tab.export': '导出',
    'settings.tab.tokens': '令牌',
    'settings.tab.webhook': 'Webhook',
    'settings.account.title': '账户设置',
    'settings.account.subtitle': '管理您的账户凭证和密码。',
    'settings.export.title': '导出设置',
    'settings.export.subtitle': '配置导出路径、平台和拉取行为。',
    'settings.tokens.title': '访问令牌',
    'settings.tokens.subtitle': '配置容器镜像仓库的身份验证令牌。',
    'settings.webhook.title': 'Webhook 通知',
    'settings.webhook.subtitle': '配置拉取完成和失败的通知。',
    'settings.loading': '加载配置中...',
    'settings.save': '保存',
    'settings.saving': '保存中...',
    'settings.saved': '已保存',
    'settings.failed': '失败',
    'settings.test': '测试',
    'settings.testing': '测试中...',
    'settings.sent': '已发送',
    'settings.password.success': '密码修改成功',
    'settings.password.minLength': '新密码至少需要6个字符',
    'settings.password.mismatch': '两次输入的新密码不一致',
    'settings.password.old': '旧密码',
    'settings.password.oldHint': '输入您当前的密码。',
    'settings.password.oldPlaceholder': '输入旧密码',
    'settings.password.new': '新密码',
    'settings.password.newHint': '新密码至少需要6个字符。',
    'settings.password.newPlaceholder': '输入新密码',
    'settings.password.confirm': '确认新密码',
    'settings.password.confirmHint': '再次输入新密码以确认。',
    'settings.password.confirmPlaceholder': '确认新密码',
    'settings.export.directory': '导出目录',
    'settings.export.directoryHint': '拉取的镜像保存目录。',
    'settings.export.browse': '浏览',
    'settings.export.platform': '默认平台',
    'settings.export.platformHint': '镜像拉取的目标架构。',
    'settings.export.concurrent': '并发拉取数',
    'settings.export.concurrentHint': '最大同时拉取数（1-10）。',
    'settings.export.gzip': 'Gzip 压缩',
    'settings.export.gzipHint': '压缩级别（1-9）。',
    'settings.export.retries': '最大重试次数',
    'settings.export.retriesHint': '设为0表示无限重试。',
    'settings.export.retryInterval': '重试间隔（秒）',
    'settings.export.retryIntervalHint': '每次重试之间的秒数。',
    'settings.webhook.enable': '启用 Webhooks',
    'settings.webhook.enableHint': '拉取完成时发送 POST 请求。',
    'settings.webhook.enabled': '已启用',
    'settings.webhook.disabled': '已禁用',
    'settings.webhook.type': 'Webhook 类型',
    'settings.webhook.typeHint': '接收通知的平台。',
    'settings.webhook.url': 'Webhook URL',
    'settings.webhook.urlHint': '接收通知的 POST 端点。',
    'settings.tokens.none': '未配置任何镜像仓库令牌',
    'settings.tokens.add': '添加镜像仓库令牌',
    'settings.tokens.addAnother': '添加其他仓库',
    'settings.tokens.select': '选择要添加的镜像仓库：',
    'settings.tokens.allConfigured': '所有镜像仓库都已配置',
    'settings.tokens.remove': '移除',
    'settings.tokens.close': '关闭',

    'token.dockerhub.name': 'Docker Hub',
    'token.dockerhub.hint': 'Docker Hub 的用户名和访问令牌。在账户设置 > 安全中创建令牌。',
    'token.dockerhub.username': '用户名',
    'token.dockerhub.token': '访问令牌',
    'token.ghcr.name': 'GitHub Container Registry (ghcr.io)',
    'token.ghcr.hint': '具有 read:packages 权限的个人访问令牌。即使是公开镜像也需要。',
    'token.ghcr.token': 'ghp_xxxxxxxxxxxx',
    'token.quay.name': 'Quay.io',
    'token.quay.hint': 'Quay.io 镜像仓库的访问令牌。创建机器人账户或使用 OAuth 令牌。',
    'token.quay.token': 'Quay 访问令牌',
    'token.acr.name': '阿里云容器镜像服务',
    'token.acr.hint': '阿里云容器镜像服务 的用户名和密码。',
    'token.acr.username': '用户名',
    'token.acr.password': '密码',
    'token.ecr.name': 'AWS ECR',
    'token.ecr.hint': 'AWS ECR 的凭证。默认区域为 us-east-1。',
    'token.ecr.accessKey': 'Access Key ID',
    'token.ecr.secretKey': 'Secret Access Key',
    'token.ecr.region': '区域（例如：us-east-1）',
    'token.gar.name': 'Google Artifact Registry',
    'token.gar.hint': 'Google Artifact Registry 的服务账户 JSON 密钥或 OAuth 令牌。',
    'token.gar.token': 'Google Cloud 令牌或 JSON 密钥',

    'images.title': '镜像',
    'images.add': '添加',
    'images.table.image': '镜像',
    'images.table.platform': '平台',
    'images.table.status': '状态',
    'images.table.retries': '重试',
    'images.table.exportStatus': '导出状态',
    'images.table.created': '创建时间',
    'images.table.actions': '操作',
    'images.exported': '已导出',
    'images.retry': '重试',
    'images.download': '下载',
    'images.delete': '删除',
    'images.empty.title': '从任意容器仓库拉取',
    'images.empty.desc': '从 Docker Hub、GitHub、Quay 或 GCR 添加镜像，集中管理和分发。',
    
    'modal.addImage': '添加镜像',
    'modal.batchMode': '批量模式 — 每行一个镜像',
    'modal.images': '镜像列表',
    'modal.image': '镜像',
    'modal.platforms': '平台',
    'modal.autoExport': '拉取完成后自动导出',
    'modal.cancel': '取消',
    'modal.save': '保存',
    'modal.saving': '保存中...',
    
    'logs.title': '日志',
    'logs.refresh': '刷新',
    'logs.searchPlaceholder': '搜索日志...',
    'logs.allPlatforms': '所有平台',
    'logs.allImages': '所有镜像',
    'logs.allActions': '所有操作',
    'logs.clearFilters': '清除筛选',
    'logs.table.time': '时间',
    'logs.table.image': '镜像',
    'logs.table.action': '操作',
    'logs.table.message': '消息',
    'logs.loading': '加载日志中...',
    'logs.empty.title': '未找到日志',
    'logs.empty.desc': '尝试调整筛选条件',
    'logs.empty.noLogs': '镜像处理时日志将在此显示',
    
    'stats.title': '概览',
    'stats.total': '镜像总数',
    'stats.totalDesc': '所有镜像任务',
    'stats.success': '成功',
    'stats.successDesc': '拉取成功',
    'stats.failed': '失败',
    'stats.failedDesc': '拉取失败',
    'stats.pending': '等待',
    'stats.pendingDesc': '排队或进行中',
    'stats.successRate': '成功率',
    'stats.successRateDesc': '基于 {count} 个任务',
    'stats.legend.success': '成功',
    'stats.legend.failed': '失败',
    'stats.legend.pending': '等待',
    
    'login.title': '登录',
    'login.subtitle': '输入您的凭据以访问系统',
    'login.username': '用户名',
    'login.usernamePlaceholder': '输入您的用户名',
    'login.password': '密码',
    'login.passwordPlaceholder': '输入您的密码',
    'login.rememberMe': '记住我',
    'login.forgotPassword': '忘记密码？',
    'login.submit': '登录',
    'login.submitting': '登录中...',
    'login.or': '或',
    'login.sso': '使用 SSO 登录',
    'login.newUser': '新用户？',
    'login.requestAccess': '申请访问权限',
    'login.invalidCredentials': '用户名或密码无效',
    'login.error': '发生错误，请重试。',
    'login.brandTitle': 'DockerPull',
    'login.brandDesc': '一个轻量级的 Docker 镜像管理系统，轻松拉取和管理容器镜像',
    
    'status.pending': '等待',
    'status.pulling': '拉取中',
    'status.success': '成功',
    'status.failed': '失败',
    
    'platform.amd64': 'AMD64',
    'platform.arm64': 'ARM64',
    
    'action.created': '已创建',
    'action.updated': '已更新',
    'action.pulling': '拉取中',
    'action.success': '成功',
    'action.failed': '失败',
    'action.exporting': '导出中',
    'action.exported': '已导出',
    'action.changed': '已更改',
    
    'toast.imageNoArm64': '镜像不支持 linux/arm64，仅拉取 linux/amd64',
    'toast.unableVerify': '无法验证镜像架构，继续使用所选平台',
    'toast.tasksSkipped': '{count} 个任务跳过（已存在），{added} 个任务已添加',
    'toast.tasksAdded': '已添加 {count} 个镜像任务',
    
    'copy.copied': '已复制！',
    'copy.copyName': '复制镜像名称',

    'user.admin': '管理员',
    'user.clickChange': '点击头像更换',
    'user.logout': '退出登录',
    'user.uploadValid': '请上传有效的图片文件（JPEG、PNG、GIF、WebP、BMP）',
    'user.fileSize': '文件大小不能超过10MB',

    'dirPicker.title': '选择目录',
    'dirPicker.subtitle': '选择导出镜像的保存位置',
    'dirPicker.quickAccess': '快速访问',
    'dirPicker.name': '名称',
    'dirPicker.dateModified': '修改日期',
    'dirPicker.type': '类型',
    'dirPicker.cancel': '取消',
    'dirPicker.select': '选择',
    'dirPicker.loadFailed': '加载目录失败',

    ...docTranslations.zh,
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem(STORAGE_KEY)
    if (stored === 'en' || stored === 'zh') {
      document.documentElement.setAttribute('data-lang', stored)
      document.documentElement.lang = stored === 'zh' ? 'zh-CN' : 'en'
      return stored
    }
    const browserLang = navigator.language.toLowerCase()
    const initialLang = browserLang.startsWith('zh') ? 'zh' : 'en'
    document.documentElement.setAttribute('data-lang', initialLang)
    document.documentElement.lang = initialLang === 'zh' ? 'zh-CN' : 'en'
    return initialLang
  })

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language)
    document.documentElement.setAttribute('data-lang', language)
    document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en'
  }, [language])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}